sudo: required
language: ruby
services:
- docker
branches:
  only:
  - develop
script:
- echo 'No tests? No problems.'
after_success:
- provisioning/travis_ci_and_cd/build_and_push_to_ecr.sh
#- provisioning/travis_ci_and_cd/ecs_deploy.sh # uncomment when deploys are ready
env:
  global:
  - REMOTE_IMAGE_URL=685731035297.dkr.ecr.us-east-1.amazonaws.com/cantaloupe
  - secure: "SWM4nnAcBFwzyU3t3j+1um+psJwOThb7k5pixce+9wBS+HCSp525UeT0paHAbPXeGFjLB8WFH2ByRnUtx+43hal2O/gnZbP00hWgbYFjjh2MNU1Gj08wquZCXohEzbfnhxM4bYgAzx08y2jlHlU4U7ylV86zEXX3AOJKcdBI66S95IzON677oVDgaGqC1tXjkS12sG8x+Mvd0VTw2eOcloVWjspAzz74yvnHct6xI/6ttpGNHRBfBkJ6VoNby0Z+sgtQxswLKWg8eqtP2YX4sYpoTauzYS2PMC+Fbq5wuJUVTGTlshRnAbQB34nZ6tm+MA43c2iV5wHlDuNqPlAcpQNumqrtNeTJM8m31TyP3oxZuryMGnYnH3hHUdmDfbXeDFehCuBU27e3+M2b24TCKv7nxcEXl8c9KOBFd6QkylMwYTfeXeEN8hPLTin4oBHykbLznEiN3ps7LhX2j95xP8AdLMiKXWA+z+FHBGGj/RfmZAlH6xsU3S5I49w/oZOkXLI63hTA6fcQkt/Zej0x1RkXzcjnqsXi3ABrulXTnD33v+xdP4sXhjmdRwmrfrvKR/E2FuoWmUkskbk9iISlnnXS5ogmsoWAizykyuhTriEWRsHypCwSj5C4A396ORKHADtJwfK23qmwWBNPyON30UMX9fnP8xCSvbcF1cc6a94=" # AWS_ACCESS_KEY_ID_DEVELOPMENT for nypl-dams-dev 2023-11-27
  - secure: "W8oLfwmcgSSgfLU5FW/1lo0Yu5Ys9VSLC8W7/tmY7+D8CsyCF8DgWff+QYY9JjacQ9hFJX5F7kELubTc+30Wy60l4ymbQ98Ax3Kr8vg3/CrIoTkKj7vVy0QGG1VsfQuLpEk+EoPWFpd9aH41yniEDVF6ww3X7vaFS3Y8X9ePfeqMuizHKAY6R5SE5prYSYfUzYfR9mPdDd1kC6hkxAnUSJncy0vs74DXE8ckuMFY+a9of0z+mkem7Ykbu7Ajhg2I+xWsTYY2DYdWOEA4RzKZjrFT1S/92qx87pemDiRX6tDLwVaN4g7di/FfLfwW/0HngGmsr+7273KVUrO+HfuE3SlHEs40cbv79f80xfcxuybgK7QOuWvdQxfqWILzMaoPoRpodiYmYnaN5fem7hrx2nWmrqWToeFlrRpz3SCHSrMqXJWs/FMnOGkT9cufLxjW3w6Y0VqjwbXjuctk88yHwkofwQtUHfWie57klMt9VpnK8cztTrkWkyuXRvtHZXe4MRX54EeuUc88pd+jpR7RZyQqzaKMTYbdNwumj6YKnx+LckQMFHs2syEhgtVRRm984e/+7NlHIvg6lJhffAli7flPguWuII5NY9eHbzv0ThpHKRRFFBkXtPmEZtelKY3We6tmhgYa2jv+K6muKdiARmJ13Guh73Di0B7e7CdwuS0=" # AWS_SECRET_ACCESS_KEY_DEVELOPMENT for nypl-dams-dev 2023-11-27

