version: '3.4'
services:
  cantaloupe:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env
    volumes:
      - './cantaloupe:/usr/src/cantaloupe'
      - './cantaloupe/cache:/usr/src/cantaloupe/cache'
    ports:
      - '8182:8182'
