version: '3.4'
services:
  cantaloupe:
    build: .
    env_file:
      - ./.env
    volumes:
      - './images:/var/www/images.nypl.org'
      - './cache:/usr/src/cantaloupe/cache'
    ports:
      - '8182:8182'
