version: '3.4'
services:
  cantaloupe:
    build: .
    env_file:
      - ./.env
    volumes:
      - './images:/var/www/images.nypl.org'
      - './cache:/ifs/prod/iiif-imagecache'
    ports:
      - '8182:8182'

  shim:
    build: ./nginx-configs
    environment:
      IIIF_HOST: http://172.16.1.195:8182/iiif/2/
    ports:
      - "8080:80"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/setup:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
