version: '3.4'
services:
  filestore-db:
    build:
      context: ../filestore_databases_docker
      dockerfile: Dockerfile
    volumes:
      - ./database-data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
