services:
  cantaloupe:
    build: .
    env_file:
      - ./.env
    volumes:
      - 'repo-nfs-volume:/ifs/prod/repo'
      - 'cache-nfs-volume:/ifs/prod/iiif-imagecache'
      - './images:/var/www/images.nypl.org'
    ports:
      - '8182:8182'
      - "8080:8080"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/setup:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  repo-nfs-volume:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=ica.repo.nypl.org,vers=4,soft'
      device: ':/ifs/prod/repo'
  cache-nfs-volume:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=ica.repo.nypl.org,vers=4,soft'
      device: ':/ifs/prod/iiif-imagecache'
