services:
  cantaloupe:
    build: .
    env_file:
      - ./.env
    volumes:
      - './images:/usr/src/app'
      - './cache:/ifs/prod/iiif-imagecache'
      - './repo:/ifs/prod/repo'
    ports:
      - '8182:8182'
      - "8080:8080"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/setup:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
