version: '3.4'
services:
  cantaloupe:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    # volumes:
    #   - './cantaloupe:/cantaloupe'
    ports:
      - '8182:8182'
